micronaut:
  application:
    name: praticando
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/praticando
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
